sudo: required
language:
  - node_js
node_js:
  - "10"
addons:
  - chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    # specifies that chrome should be installed, this is necessary for the angular tests
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
after_success:
  - echo "success!"
