sudo: required
language:
  - node_js
node_js:
  - "10"
services:
  - docker
addons:
  - chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    # specifies that chrome should be installed, this is necessary for the angular tests
jobs:
  include:
    - stage: unit test
      install:
        - npm install
        - npm audit fix
      script:
        - npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
    - stage: build docker image
      script:
        - npm run build
        - sh .travis/deploy_dockerhub.sh
